var invert = require('invert-obj');

function MatchType (matchType) {
  this.message = matchType;
}

MatchType.prototype.value = function () {
  return this.message;
};


MatchType.Keys = {
  'EXACT_MATCH_ON_TRADE_DATE_STOCK_SYMBOL_QUANTITY_PRICE_TRADE_TYPE_AND_SPECIAL_TRADE_INDICATOR_PLUS_FOUR_BADGES_AND_EXECUTION_TIME': 'A1',
  'EXACT_MATCH_ON_TRADE_DATE_STOCK_SYMBOL_QUANTITY_PRICE_TRADE_TYPE_AND_SPECIAL_TRADE_INDICATOR_PLUS_FOUR_BADGES': 'A2',
  'EXACT_MATCH_ON_TRADE_DATE_STOCK_SYMBOL_QUANTITY_PRICE_TRADE_TYPE_AND_SPECIAL_TRADE_INDICATOR_PLUS_TWO_BADGES_AND_EXECUTION_TIME': 'A3',
  'EXACT_MATCH_ON_TRADE_DATE_STOCK_SYMBOL_QUANTITY_PRICE_TRADE_TYPE_AND_SPECIAL_TRADE_INDICATOR_PLUS_TWO_BADGES': 'A4',
  'EXACT_MATCH_ON_TRADE_DATE_STOCK_SYMBOL_QUANTITY_PRICE_TRADETYPE_AND_SPECIAL_TRADE_INDICATOR_PLUS_EXECUTION_TIME': 'A5',
  'ACT_ACCEPTED_TRADE': 'M3',
  'ACT_DEFAULT_TRADE': 'M4',
  'ACT_DEFAULT_AFTER_M2': 'M5',
  'ACT_M6_MATCH': 'M6',
  'COMPARED_RECORDS_RESULTING_FROM_STAMPED_ADVISORIES_OR_SPECIALIST_ACCEPTS_PAIR_OFFS': 'AQ',
  'EXACT_MATCH_ON_TRADE_DATE_STOCK_SYMBOL_QUANTITY_PRICE_TRADE_TYPE_AND_SPECIAL_TRADE_INDICATOR_MINUS_BADGES_AND_TIMES_ACT_M1_MATCH': 'M1',
  'SUMMARIZED_MATCH_MINUS_BADGES_AND_TIMES_ACT_M2_MATCH': 'M2',
  'OCS_LOCKED_IN_NON_ACT': 'MT',
  'SUMMARIZED_MATCH_USING_A1_EXACT_MATCH_CRITERIA_EXCEPT_QUANTITY_IS_SUMMARIED': 'S1',
  'SUMMARIZED_MATCH_USING_A2_EXACT_MATCH_CRITERIA_EXCEPT_QUANTITY_IS_SUMMARIZED': 'S2',
  'SUMMARIZED_MATCH_USING_A3_EXACT_MATCH_CRITERIA_EXCEPT_QUANTITY_IS_SUMMARIZED': 'S3',
  'SUMMARIZED_MATCH_USING_A4_EXACT_MATCH_CRITERIA_EXCEPT_QUANTITY_IS_SUMMARIZED': 'S4',
  'SUMMARIZED_MATCH_USING_A5_EXACT_MATCH_CRITERIA_EXCEPT_QUANTITY_IS_SUMMARIZED': 'S5',
  'ONE_PARTY_TRADE_REPORT': '1',
  'TWO_PARTY_TRADE_REPORT': '2',
  'CONFIRMED_TRADE_REPORT': '3',
  'AUTO_MATCH': '4',
  'CROSS_AUCTION': '5',
  'COUNTER_ORDER_SELECTION': '6',
  'CALL_AUCTION': '7',
  'ISSUING_BUY_BACK_AUCTION': '8',
};

MatchType.Tag = '574';

MatchType.Type = 'STRING';

MatchType.Values = invert(MatchType.Keys);

module.exports = MatchType;