var invert = require('invert-obj');

function Rule80A (rule80A) {
  this.message = rule80A;
}

Rule80A.prototype.value = function () {
  return this.message;
};


Rule80A.Keys = {
  'AGENCY_SINGLE_ORDER': 'A',
  'SHORT_EXEMPT_TRANSACTION_B': 'B',
  'PROPRIETARY_NON_ALGORITHMIC_PROGRAM_TRADE': 'C',
  'PROGRAM_ORDER_INDEX_ARB_FOR_MEMBER_FIRM_ORG': 'D',
  'SHORT_EXEMPT_TRANSACTION_FOR_PRINCIPAL': 'E',
  'SHORT_EXEMPT_TRANSACTION_F': 'F',
  'SHORT_EXEMPT_TRANSACTION_H': 'H',
  'INDIVIDUAL_INVESTOR_SINGLE_ORDER': 'I',
  'PROPRIETARY_ALGORITHMIC_PROGRAM_TRADING': 'J',
  'AGENCY_ALGORITHMIC_PROGRAM_TRADING': 'K',
  'SHORT_EXEMPT_TRANSACTION_FOR_MEMBER_COMPETING_MARKET_MAKER_AFFLIATED_WITH_THE_FIRM_CLEARING_THE_TRADE': 'L',
  'PROGRAM_ORDER_INDEX_ARB_FOR_OTHER_MEMBER': 'M',
  'AGENT_FOR_OTHER_MEMBER_NON_ALGORITHMIC_PROGRAM_TRADE': 'N',
  'PROPRIETARY_TRANSACTIONS_FOR_COMPETING_MARKET_MAKER_THAT_IS_AFFILIATED_WITH_THE_CLEARING_MEMBER': 'O',
  'PRINCIPAL': 'P',
  'TRANSACTIONS_FOR_THE_ACCOUNT_OF_A_NON_MEMBER_COMPTING_MARKET_MAKER': 'R',
  'SPECIALIST_TRADES': 'S',
  'TRANSACTIONS_FOR_THE_ACCOUNT_OF_AN_UNAFFILIATED_MEMBERS_COMPETING_MARKET_MAKER': 'T',
  'AGENCY_INDEX_ARBITRAGE': 'U',
  'ALL_OTHER_ORDERS_AS_AGENT_FOR_OTHER_MEMBER': 'W',
  'SHORT_EXEMPT_TRANSACTION_FOR_MEMBER_COMPETING_MARKET_MAKER_NOT_AFFILIATED_WITH_THE_FIRM_CLEARING_THE_TRADE': 'X',
  'AGENCY_NON_ALGORITHMIC_PROGRAM_TRADE': 'Y',
  'SHORT_EXEMPT_TRANSACTION_FOR_NON_MEMBER_COMPETING_MARKET_MAKER': 'Z',
};

Rule80A.Tag = '47';

Rule80A.Type = 'CHAR';

Rule80A.Values = invert(Rule80A.Keys);

module.exports = Rule80A;