var invert = require('invert-obj');

function StipulationType (stipulationType) {
  this.message = stipulationType;
}

StipulationType.prototype.value = function () {
  return this.message;
};


StipulationType.Keys = {
  'ABSOLUTE_PREPAYMENT_SPEED': 'ABS',
  'ALTERNATIVE_MINIMUM_TAX': 'AMT',
  'AUTO_REINVESTMENT_AT_RATE_OR_BETTER': 'AUTOREINV',
  'BANK_QUALIFIED': 'BANKQUAL',
  'BARGAIN_CONDITIONS': 'BGNCON',
  'COUPON_RANGE': 'COUPON',
  'CONSTANT_PREPAYMENT_PENALTY': 'CPP',
  'CONSTANT_PREPAYMENT_RATE': 'CPR',
  'CONSTANT_PREPAYMENT_YIELD': 'CPY',
  'ISO_CURRENCY_CODE': 'CURRENCY',
  'CUSTOM_START_END_DATE': 'CUSTOMDATE',
  'GEOGRAPHICS_AND_RANGE': 'GEOG',
  'VALUATION_DISCOUNT': 'HAIRCUT',
  'FINAL_CPR_OF_HOME_EQUITY_PREPAYMENT_CURVE': 'HEP',
  'INSURED': 'INSURED',
  'YEAR_OR_YEAR_MONTH_OF_ISSUE': 'ISSUE',
  'ISSUERS_TICKER': 'ISSUER',
  'ISSUE_SIZE_RANGE': 'ISSUESIZE',
  'LOOKBACK_DAYS': 'LOOKBACK',
  'EXPLICIT_LOT_IDENTIFIER': 'LOT',
  'LOT_VARIANCE': 'LOTVAR',
  'MATURITY_YEAR_AND_MONTH': 'MAT',
  'MATURITY_RANGE': 'MATURITY',
  'MAXIMUM_SUBSTITUTIONS': 'MAXSUBS',
  'PERCENT_OF_MANUFACTURED_HOUSING_PREPAYMENT_CURVE': 'MHP',
  'MINIMUM_DENOMINATION': 'MINDNOM',
  'MINIMUM_INCREMENT': 'MININCR',
  'MINIMUM_QUANTITY': 'MINQTY',
  'MONTHLY_PREPAYMENT_RATE': 'MPR',
  'PAYMENT_FREQUENCY_CALENDAR': 'PAYFREQ',
  'NUMBER_OF_PIECES': 'PIECES',
  'POOLS_MAXIMUM': 'PMAX',
  'PERCENT_OF_PROSPECTUS_PREPAYMENT_CURVE': 'PPC',
  'POOLS_PER_LOT': 'PPL',
  'POOLS_PER_MILLION': 'PPM',
  'POOLS_PER_TRADE': 'PPT',
  'PRICE_RANGE': 'PRICE',
  'PRICING_FREQUENCY': 'PRICEFREQ',
  'PRODUCTION_YEAR': 'PROD',
  'CALL_PROTECTION': 'PROTECT',
  'PERCENT_OF_BMA_PREPAYMENT_CURVE': 'PSA',
  'PURPOSE': 'PURPOSE',
  'BENCHMARK_PRICE_SOURCE': 'PXSOURCE',
  'RATING_SOURCE_AND_RANGE': 'RATING',
  'TYPE_OF_REDEMPTION': 'REDEMPTION',
  'RESTRICTED': 'RESTRICTED',
  'MARKET_SECTOR': 'SECTOR',
  'SECURITY_TYPE_INCLUDED_OR_EXCLUDED': 'SECTYPE',
  'SINGLE_MONTHLY_MORTALITY': 'SMM',
  'STRUCTURE': 'STRUCT',
  'SUBSTITUTIONS_FREQUENCY': 'SUBSFREQ',
  'SUBSTITUTIONS_LEFT': 'SUBSLEFT',
  'FREEFORM_TEXT': 'TEXT',
  'TRADE_VARIANCE': 'TRDVAR',
  'WEIGHTED_AVERAGE_COUPON': 'WAC',
  'WEIGHTED_AVERAGE_LIFE_COUPON': 'WAL',
  'WEIGHTED_AVERAGE_LOAN_AGE': 'WALA',
  'WEIGHTED_AVERAGE_MATURITY': 'WAM',
  'WHOLE_POOL': 'WHOLE',
  'YIELD_RANGE': 'YIELD',
  'AVERAGE_FICO_SCORE': 'AVFICO',
  'AVERAGE_LOAN_SIZE': 'AVSIZE',
  'MAXIMUM_LOAN_BALANCE': 'MAXBAL',
  'POOL_IDENTIFIER': 'POOL',
  'TYPE_OF_ROLL_TRADE': 'ROLLTYPE',
  'REFERENCE_TO_ROLLING_OR_CLOSING_TRADE': 'REFTRADE',
  'PRINCIPAL_OF_ROLLING_OR_CLOSING_TRADE': 'REFPRIN',
  'INTEREST_OF_ROLLING_OR_CLOSING_TRADE': 'REFINT',
  'AVAILABLE_OFFER_QUANTITY_TO_BE_SHOWN_TO_THE_STREET': 'AVAILQTY',
  'BROKERS_SALES_CREDIT': 'BROKERCREDIT',
  'OFFER_PRICE_TO_BE_SHOWN_TO_INTERNAL_BROKERS': 'INTERNALPX',
  'OFFER_QUANTITY_TO_BE_SHOWN_TO_INTERNAL_BROKERS': 'INTERNALQTY',
  'THE_MINIMUM_RESIDUAL_OFFER_QUANTITY': 'LEAVEQTY',
  'MAXIMUM_ORDER_SIZE': 'MAXORDQTY',
  'ORDER_QUANTITY_INCREMENT': 'ORDRINCR',
  'PRIMARY_OR_SECONDARY_MARKET_INDICATOR': 'PRIMARY',
  'BROKER_SALES_CREDIT_OVERRIDE': 'SALESCREDITOVR',
  'TRADERS_CREDIT': 'TRADERCREDIT',
  'DISCOUNT_RATE': 'DISCOUNT',
  'YIELD_TO_MATURITY': 'YTM',
};

StipulationType.Tag = '233';

StipulationType.Type = 'STRING';

StipulationType.Values = invert(StipulationType.Keys);

module.exports = StipulationType;