var invert = require('invert-obj');

function YieldType (yieldType) {
  this.message = yieldType;
}

YieldType.prototype.value = function () {
  return this.message;
};


YieldType.Keys = {
  'AFTER_TAX_YIELD': 'AFTERTAX',
  'ANNUAL_YIELD': 'ANNUAL',
  'YIELD_AT_ISSUE': 'ATISSUE',
  'YIELD_TO_AVG_MATURITY': 'AVGMATURITY',
  'BOOK_YIELD': 'BOOK',
  'YIELD_TO_NEXT_CALL': 'CALL',
  'YIELD_CHANGE_SINCE_CLOSE': 'CHANGE',
  'CLOSING_YIELD': 'CLOSE',
  'COMPOUND_YIELD': 'COMPOUND',
  'CURRENT_YIELD': 'CURRENT',
  'GVNT_EQUIVALENT_YIELD': 'GOVTEQUIV',
  'TRUE_GROSS_YIELD': 'GROSS',
  'YIELD_WITH_INFLATION_ASSUMPTION': 'INFLATION',
  'INVERSE_FLOATER_BOND_YIELD': 'INVERSEFLOATER',
  'MOST_RECENT_CLOSING_YIELD': 'LASTCLOSE',
  'CLOSING_YIELD_MOST_RECENT_MONTH': 'LASTMONTH',
  'CLOSING_YIELD_MOST_RECENT_QUARTER': 'LASTQUARTER',
  'CLOSING_YIELD_MOST_RECENT_YEAR': 'LASTYEAR',
  'YIELD_TO_LONGEST_AVERAGE_LIFE': 'LONGAVGLIFE',
  'MARK_TO_MARKET_YIELD': 'MARK',
  'YIELD_TO_MATURITY': 'MATURITY',
  'YIELD_TO_NEXT_REFUND': 'NEXTREFUND',
  'OPEN_AVERAGE_YIELD': 'OPENAVG',
  'PREVIOUS_CLOSE_YIELD': 'PREVCLOSE',
  'PROCEEDS_YIELD': 'PROCEEDS',
  'YIELD_TO_NEXT_PUT': 'PUT',
  'SEMI_ANNUAL_YIELD': 'SEMIANNUAL',
  'YIELD_TO_SHORTEST_AVERAGE_LIFE': 'SHORTAVGLIFE',
  'SIMPLE_YIELD': 'SIMPLE',
  'TAX_EQUIVALENT_YIELD': 'TAXEQUIV',
  'YIELD_TO_TENDER_DATE': 'TENDER',
  'TRUE_YIELD': 'TRUE',
  'YIELD_VALUE_OF_1_32': 'VALUE1_32',
  'YIELD_TO_WORST': 'WORST',
};

YieldType.Tag = '235';

YieldType.Type = 'STRING';

YieldType.Values = invert(YieldType.Keys);

module.exports = YieldType;